name: Pipeline
on: [push]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload coverage to artifact
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage

      - name: Build
        run: npm run build

      - name: Notify on email success or failure
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.repository }} build ${{ github.sha }}
          body: ${{ job.status }}
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          content_type: text/plain
